steps:
  # Step 1: Initialize Terraform
  - name: "hashicorp/terraform:1.5.7"
    dir: "terraform"
    args: ["init"]

  # Step 2: Run Terraform Plan
  - name: "hashicorp/terraform:1.5.7"
    dir: "terraform"
    args: ["plan", "-no-color"]

options:
  logging: CLOUD_LOGGING_ONLY
