project_name        = "Serverless Data Pipeline"
project_id          = "serverless-data-pipeline-111"
region              = "europe-west1"
billing_account     = "017F1D-A6D67E-93CD39"
org_id              = "97533724144"
folder_id           = "501022756737"
dataset_id          = "processed_weather_data"
table_id            = "transformed_weather_data"
alert_email_address = "quentin.st-pierre@devoteam.com"
github_owner        = "quentin-stpierre"
github_repo         = "serverless_data_pipeline"

# URL = "https://api.openweathermap.org/data/2.5/weather?lat=50.8503&lon=4.3517&units=metric&appid={YOUR_API_KEY}"
